version: '3.7'
services:

  scheduler-database-server:
    build:
      context: ./scheduler-database-server
      dockerfile: Dockerfile
    image: scheduler-database-server
    restart: always
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432

  scheduler-auth-server:
    environment:
      BACKEND_SERVER_ID: $BACKEND_SERVER_ID
      BACKEND_SERVER_PASSWORD: $BACKEND_SERVER_PASSWORD
      DB_DRIVER_CLASS_NAME: $DB_DRIVER_CLASS_NAME
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWD: $DB_PASSWD
    build:
      context: ./scheduler-auth-server
      dockerfile: Dockerfile
    image: scheduler-auth-server
    restart: always
    ports:
      - 5000:5000

  scheduler-gateway-server:
    build:
      context: ./scheduler-gateway-server
      dockerfile: Dockerfile
    image: scheduler-gateway-server
    restart: always
    ports:
      - 80:4000

  scheduler-backend-server:
    environment:
      USER_INFO_URI: $USER_INFO_URI
      ACCESS_TOKEN_URI: $ACCESS_TOKEN_URI
      BACKEND_SERVER_ID: $BACKEND_SERVER_ID
      BACKEND_SERVER_PASSWORD: $BACKEND_SERVER_PASSWORD
      DB_DRIVER_CLASS_NAME: $DB_DRIVER_CLASS_NAME
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWD: $DB_PASSWD
    build:
      context: ./scheduler-backend-server
      dockerfile: Dockerfile
    image: scheduler-backend-server
    restart: always
    volumes:
      - ${DEP_ICON_VOLUME_PATH}:/app/department-icons
    depends_on:
      - scheduler-auth-server
    ports:
      - 8080:8080