version: '3.7'
services:

  scheduler-database-server:
    build:
      context: ./scheduler-database-server
      dockerfile: Dockerfile
    image: scheduler-database-server
    hostname: scheduler-database-server
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${GRAYLOG_HOST}:${GRAYLOG_GELF_PORT}"
        tag: "schedulerdb"
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432

  scheduler-auth-server:
    environment:
      GRAYLOG_HOST: $GRAYLOG_HOST
      GRAYLOG_GELF_PORT: $GRAYLOG_GELF_PORT
      BACKEND_SERVER_ID: $BACKEND_SERVER_ID
      BACKEND_SERVER_PASSWORD: $BACKEND_SERVER_PASSWORD
      DB_DRIVER_CLASS_NAME: $DB_DRIVER_CLASS_NAME
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWD: $DB_PASSWD
    build:
      context: ./scheduler-auth-server
      dockerfile: Dockerfile
    image: scheduler-auth-server
    hostname: scheduler-auth-server
    restart: always
    volumes:
      - ${LOG_VOLUME_PATH}:/logs
    ports:
      - 5000:5000

  scheduler-gateway-server:
    build:
      context: ./scheduler-gateway-server
      dockerfile: Dockerfile
    image: scheduler-gateway-server
    hostname: scheduler-gateway-server
    restart: always
    ports:
      - 4000:4000

  scheduler-backend-server:
    environment:
      GRAYLOG_HOST: $GRAYLOG_HOST
      GRAYLOG_GELF_PORT: $GRAYLOG_GELF_PORT
      USER_INFO_URI: $USER_INFO_URI
      ACCESS_TOKEN_URI: $ACCESS_TOKEN_URI
      BACKEND_SERVER_ID: $BACKEND_SERVER_ID
      BACKEND_SERVER_PASSWORD: $BACKEND_SERVER_PASSWORD
      DB_DRIVER_CLASS_NAME: $DB_DRIVER_CLASS_NAME
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWD: $DB_PASSWD
    build:
      context: ./scheduler-backend-server
      dockerfile: Dockerfile
    image: scheduler-backend-server
    hostname: scheduler-backend-server
    restart: always
    volumes:
      - ${LOG_VOLUME_PATH}:/logs
    depends_on:
      - scheduler-auth-server
    ports:
      - 8080:8080

  scheduler-frontend-server:
    build:
      context: ./scheduler-frontend-server
      dockerfile: Dockerfile
    image: scheduler-frontend-server
    hostname: scheduler-frontend-server
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${GRAYLOG_HOST}:${GRAYLOG_GELF_PORT}"
        tag: "nginx"
    volumes:
      - ${FRONTEND_VOLUME_PATH}:/usr/share/nginx/html
    ports:
      - 80:80 #50680
