security:
  oauth2:
    client:
      clientId: ${ADMIN_SERVICE_ID}
      clientSecret: ${ADMIN_SERVICE_PASSWORD}
      accessTokenUri: ${ACCESS_TOKEN_URI}
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: ${USER_INFO_URI}
spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    date-format: "yyyy-MM-dd"