spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write-dates-as-timestamps: false
      date-format: "yyyy-MM-dd"