spring:
  application:
    name: scheduler-auth-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jackson:
    date-format: "yyyy-MM-dd"
server:
  port: 5000
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
