spring:
  application:
    name: scheduler-auth-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jackson:
    date-format: "yyyy-MM-dd"
server:
  port: 5000
  servlet:
    context-path: /
logging:
  level:
    org.springframework.web: TRACE
